### ISSUE TITLE
Invalid push subscriptions need to be removed automatically

### ISSUE THREAD

**Issue by bp2008** [bp2008/ErrorTracker#9]
```
Failed to send push notification.
WebPush.WebPushException: Subscription no longer valid
   at WebPush.WebPushClient.HandleResponse(HttpResponseMessage response, PushSubscription subscription)
   at WebPush.WebPushClient.SendNotification(PushSubscription subscription, String payload, Dictionary`2 options)
   at WebPush.WebPushClient.SendNotification(PushSubscription subscription, String payload, VapidDetails vapidDetails)
   at ErrorTrackerServer.PushManager.doPushBackgroundWork() in C:\Users\brpea\Source\Repos\ErrorTracker\ErrorTrackerServer\Code\PushManager.cs:line 114
```

**Comment by bp2008** [comment]
Fixed in [ErrorTracker 1.8](https://github.com/bp2008/ErrorTracker/releases/tag/1.8).
